on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ["24"]
        rebar3: ["3.18.0"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - run: sudo apt-get -y install protobuf-compiler libprotobuf-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}
      - run: |
          rebar3 fmt --check && rebar3 dialyzer && rebar3 compile && rebar3 edoc
